;;;; Giacomo Ritucci, 00.01 di sabato 15 dicembre 2007

;;; Problem 2
;;;
;;; Each new term in the Fibonacci sequence is generated by adding the
;;; previous two terms. By starting with 1 and 2, the first 10 terms will be:
;;;
;;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;;
;;; Find the sum of all the even-valued terms in the sequence which do not
;;; exceed one million.

(print (do ((sum 0)
	    (cur 0 next)
	    (next 1 (+ cur next)))
	 ((>= cur 1000000) sum)
	 (if (= 0 (mod cur 2)) (incf sum cur))))
