/* Giacomo Ritucci <ritucci@cs.unibo.it>  */

#ifndef PROBLEMS_H
#define PROBLEMS_H

/* Problem 1
 *
 * Add all the natural numbers below 1000 that are multiples of 3 or 5.
 *
 * If we list all the natural numbers below 10 that are multiples of 3 or 5,
 * we get 3, 5, 6 and 9. The sum of these multiples is 23.
 *
 * Find the sum of all the multiples of 3 or 5 below 1000. */

void
problem_1 (void);


/* Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not
 * exceed one million. */

void
problem_2 (void);


/* Problem 3
 *
 * The prime factors of 13195 are 5, 7, 13 and 29.
 *
 * What is the largest prime factor of the number 317584931803? */

void
problem_3 (void);


/* Problem 20
 *
 * n! means n × (n − 1) × ... × 3 × 2 × 1
 *
 * Find the sum of the digits in the number 100! */

void
problem_20 (void);


#endif /* PROBLEMS_H */
