/* Giacomo Ritucci <ritucci@cs.unibo.it>
 * 
 * Problem 2 - http://projecteuler.net/
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not
 * exceed one million. */

#include <stdio.h>


#define     ONE_MILLION     1000000


static int
sumEvenTermsFib (const int max) {

	int sum = 0;
	int last = 0;
	int n = 2;
	int nextEven;

	while (n < ONE_MILLION) {
		sum += n;
		nextEven = n * 4 + last;
		last = n;
		n = nextEven;
	}

	return sum;
}


void
problem_2 (void) {
	printf ("Answer: %d\n", sumEvenTermsFib (ONE_MILLION));
}
