(problem :id 1
	 :title "Add all the natural numbers below one thousand that are multiples of 3 or 5."
	 :description "If we list all the natural numbers below 10 that are multiplies of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiplies is 23.

Find the sum of all the multiplies of 3 or 5 below 1000")

(problem :id 2
	 :title "Find the sum of all the even-valued terms in the Fibonacci sequence which do not exceed four million."
	 :description "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.")