#!/bin/bash
#
# Giacomo Ritucci <ritucci@cs.unibo.it>

cat << END_DESCR
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed
one million.

END_DESCR

echo go |
	awk '
	{
		n = 2
	       	while (n < 1000000) {
			sum += n
		       	newN = (n * 4) + last
			last = n
			n = newN
		}
	}

	END {
		print "Answer: " sum 
	}'
